/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Thrift.Contract.Contract.UserContract
{
  public enum SaveResult
  {
    SUCCESS = 0,
    FAILED = 1,
  }
}
